name: genome-profiler
channels:
  - bioconda
  - conda-forge
  # TODO are these needed?
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python
  - bio
  - ratelimit
  - requests-toolbelt
  - python-dotenv
  - abricate>=1.0.1
  - isescan
  - mash
  - integron_finder
  - ectyper
  - diamond
  - ncbi-datasets-cli
  - lxml
  - pycurl
