import argparse
import configparser
from multiprocessing import cpu_count
from configparser import ConfigParser
import gui_frontend
import sys


def create_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="GenomeProfiler",
        description="A tool to automate genome feature profiling and visualization.",
        epilog="""
Available Tools (use with --include-tools):
  abricate       - Run abricate for resistance gene profiling.
  isescan        - Run ISEScan to identify insertion sequences.
  mobileog       - Run MobileOG-db analysis.
  ectyper        - Run ECTyper for serotyping.
  tncentral      - Run BLASTn search against TnCentral.
  integron       - Run Integron Finder.
  islandviewer   - Submit genome to IslandViewer for island prediction.
  plsdb          - Use PLSDB for plasmid similarity screening.
  phastest       - Run local PHASTEST search for phage regions.
  parser         - Parse tool outputs for visualization (enabled by default in GUI).

Examples:
  python cli_main.py NZ_CP000000
  python cli_main.py NZ_CP000000 --include-tools abricate parser --timestamped-output
  python cli_main.py --help
        """,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        
    )

    parser.add_argument(
        "accessions",
        nargs="*",
        help="NCBI accession(s) to process (optional if using --fasta or --genbank)",
    )
    parser.add_argument(
        "--setup",
        action="store_true",
        help="Download resources required by tools, such as databases. NOTE: Run using this once before using other options.",
    )
    parser.add_argument(
        "-g",
        "--gui",
        action="store_true",
        help="Run GenomeProfiler in graphical mode. NOTE: This will ignore all other arguments.",
    )
    parser.add_argument(
        "-t",
        "--include",
        nargs="*",
        default=[],
        help="Run these tools on the accessions.",
    )
    parser.add_argument(
        "-a",
        "--all-tools",
        action="store_true",
        help="Run all available tools on the accessions."
    )
    parser.add_argument(
        "--exclude",
        nargs="*",
        default=[],
        help="Do not run these tools on the accessions. NOTE: If a tool is included and excluded, it will not be included."
    )
    parser.add_argument(
        "--fasta",
        help="Optional local FASTA file to use instead of fetching from NCBI",
    )
    parser.add_argument(
        "--genbank",
        help="Optional local GenBank file to use instead of fetching from NCBI",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=int(cpu_count() / 2),
        help=f"Number of concurrent workers (default: {int(cpu_count() / 2)}, half of CPU count)",
    )
    parser.add_argument(
        "--output-dir",
        help="Base directory to store results (overrides: output_base in config; default: output_GenomeProfiler)",
    )
    parser.add_argument(
        "--resources-dir",
        nargs=1,
        default="resources_GenomeProfiler",
        help="Path to resources directory generated by --setup (default: resources_GenomeProfiler)",
    )
    parser.add_argument(
        "--config-dir",
        nargs=1,
        default="config_GenomeProfiler.ini",
        help="Path to configuration file generated by --setup (default: config_GenomeProfiler.ini)",
    )

    return parser


def open_gui():
    gui_frontend.main()
    sys.exit(0)


def load_config():
    config = ConfigParser()
    if not config.read(CONFIG_FILE):
        raise FileNotFoundError(f"Missing config file: {CONFIG_FILE}")

    required_keys = [
        "output_base",
        "max_workers",
        "sleep_interval",
        "abricate_path",
        "integron_path",
        "isescan_path",
        "ectyper_path",
        "islandviewer_api_submit",
        "prodigal_path",
        "diamond_path",
        "mobileog_db_faa",
        "mobileog_db_csv",
        "nuccore_csv",  # Must point to 'nuccore.csv' with columns [NUCCORE_ACC, ASSEMBLY_UID]
        "assembly_csv",  # Must point to 'assembly.csv' with columns [ASSEMBLY_UID, ASSEMBLY_ACC]
        "plsdb_sketch_path",  # The local .msh file for MASH
    ]

    optional_defaults = {
        "plsdb_timeout": "30",
        "plsdb_max_results": "100",
        "ectyper_cores": "2",
    }

    if not config.has_section(SECTION):
        raise KeyError(f"Missing section: {SECTION}")

    missing = [key for key in required_keys if not config.has_option(SECTION, key)]
    if missing:
        raise ValueError(f"Missing required config keys: {', '.join(missing)}")

    # Set defaults for optional parameters
    for key, value in optional_defaults.items():
        if not config.has_option(SECTION, key):
            config.set(SECTION, key, value)

    return config[SECTION]


def validate_environment(config):
    checks = [
        ("abricate", [config["abricate_path"], "--version"]),
        ("integron_finder", [config["integron_path"], "--version"]),
        ("isescan", [config["isescan_path"], "--version"]),
        ("ectyper", [config["ectyper_path"], "--version"]),
        ("diamond", [config["diamond_path"], "version"]),
        ("prodigal", [config["prodigal_path"], "-v"]),
    ]

    missing = []
    for name, cmd in checks:
        try:
            subprocess.run(
                cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
            )
        except (subprocess.CalledProcessError, FileNotFoundError):
            missing.append(name)

    if missing:
        raise EnvironmentError(f"Missing tools: {', '.join(missing)}")


def resolve_config_and_args():
    cli_parser = create_argument_parser()
    config_parser = None

    args = cli_parser.parse_args()

    if len(sys.argv) == 1:
        cli_parser.print_help()
        sys.exit(0)

    if args.gui:
        open_gui()


def main():
    resolve_config_and_args()
    validate_environment()


if __name__ == "__main__":
    main()
