{% set version = "0.4.2rc12" %}

package:
  name: genome_profiler
  version: {{ version }}

source:
  url: https://github.com/Syrinx55/GenomeProfiler/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2c5adfc7559539fc861cb2062ad4bcc6c90fcb1afb75c6b90abba58929153ce9


build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - genome_profiler = genome_profiler.genome_profiler:main

requirements:
  host:
    - python >=3.10,<3.13
    - pip
  run:
    - python >=3.10,<3.13
    - ratelimit
    - requests-toolbelt
    - python-dotenv
    - lxml
    - pycurl
    - abricate >=1.0.1
    - isescan
    - mash
    - integron_finder
    - ectyper
    - diamond
    - ncbi-datasets-cli
    - pip
  run_constrained:
    - bio >=1.8  # pip-installed package

test:
  commands:
    - genome_profiler --help

about:
  home: https://github.com/Syrinx55/GenomeProfiler
  license: BSD-2-Clause-Patent
  summary: "Prokaryotic genome and plasmid profiling pipeline."

extra:
  recipe-maintainers:
    - Syrinx55
